# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_target=1.20.6
# Override minecraft_target on the command line (e.g. -Pminecraft_target=1.20.5)
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.1
loader_version=0.17.3
# Mod Properties
mod_version=2.0.0
maven_group=com.sheath
modid=hammermining
archives_base_name=HammerMining-fabric
# Dependencies
fabric_version=0.100.8+1.20.6

modmenu=10.0.0
