# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_target=1.20.4
# Override minecraft_target on the command line (e.g. -Pminecraft_target=1.20)
minecraft_version=1.20.4
yarn_mappings=1.20.4+build.1
loader_version=0.17.3
# Mod Properties
mod_version=2.0.0
maven_group=com.sheath
modid=hammermining
archives_base_name=HammerMining-fabric
# Dependencies
fabric_version=0.97.3+1.20.4

modmenu=9.0.0
